# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MP4Video-Audio-ExtractorUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(546, 471)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 521, 411))
        self.frame.setStyleSheet("border-width: 2px;"
    "border-color: beige;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 321, 171))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 301, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.sourcePath = QtWidgets.QLineEdit(self.groupBox_2)
        self.sourcePath.setGeometry(QtCore.QRect(10, 30, 191, 25))
        self.sourcePath.setStyleSheet("border-width: 2px;"
    "border-color: beige;")
        self.sourcePath.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.sourcePath.setObjectName("sourcePath")
        self.sourceButton = QtWidgets.QPushButton(self.groupBox_2)
        self.sourceButton.setGeometry(QtCore.QRect(210, 30, 80, 25))
        self.sourceButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.sourceButton.setObjectName("sourceButton")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 100, 301, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.targetPath = QtWidgets.QLineEdit(self.groupBox_3)
        self.targetPath.setGeometry(QtCore.QRect(10, 30, 191, 25))
        self.targetPath.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.targetPath.setObjectName("targetPath")
        self.targetPath.setStyleSheet("border-width: 2px;"
    "border-color: beige;")
        self.targetButton = QtWidgets.QPushButton(self.groupBox_3)
        self.targetButton.setGeometry(QtCore.QRect(210, 30, 80, 25))
        self.targetButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.targetButton.setObjectName("targetButton")
        self.processWindow1 = QtWidgets.QGroupBox(self.frame)
        self.processWindow1.setGeometry(QtCore.QRect(10, 190, 501, 201))
        self.processWindow1.setStyleSheet(
    "color: rgb(0, 0, 0);\n" 
    "font: 9pt \"FreeMono\";"
    "border-radius: 2px;")
        self.processWindow1.setObjectName("processWindow1")
        self.scrollArea = QtWidgets.QScrollArea(self.processWindow1)
        self.scrollArea.setGeometry(QtCore.QRect(0, 20, 501, 181))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 499, 179))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.processWindow = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.processWindow.setGeometry(QtCore.QRect(0, 0, 501, 181))
        font = QtGui.QFont()
        font.setFamily("FreeMono")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.processWindow.setFont(font)
        self.processWindow.setToolTip("")
        self.processWindow.setStyleSheet(
    "background-color: rgb(0, 0, 0);\n"
    "color: rgb(0, 128, 0);\n"  # This line changes the text color to green
    "font: 10pt \"FreeMono\";"
    "border-radius: 0;"
)
        self.processWindow.setObjectName("processWindow")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.startProcess = QtWidgets.QPushButton(self.frame)
        self.startProcess.setGeometry(QtCore.QRect(360, 20, 131, 71))
        self.startProcess.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.startProcess.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.startProcess.setStyleSheet(
    "QPushButton {"
    "background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #FF6347, stop:1 #DC143C);"  # Red gradient
    "border-style: outset;"
    "border-width: 2px;"
    "border-radius: 10px;"
    "border-color: beige;"
    "font: bold 12px;"
    "}"
    "QPushButton:hover {"
    "background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #FFA07A, stop:1 #FF7F50);"  # Lighter red gradient on hover
    "}"
    "QPushButton:pressed {"
    "background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #B22222, stop:1 #8B0000);"  # Darker red gradient on press
    "}"
)
        self.startProcess.setObjectName("startProcess")
        self.abortProcess = QtWidgets.QPushButton(self.frame)
        self.abortProcess.setGeometry(QtCore.QRect(360, 110, 131, 71))
        self.abortProcess.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.abortProcess.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.abortProcess.setStyleSheet(
    "QPushButton {"
    "background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #FFA500, stop:1 #FFD700);"
    "border-style: outset;"
    "border-width: 2px;"
    "border-radius: 10px;"
    "border-color: beige;"
    "font: bold 12px;"
    "}"
    "QPushButton:hover {"
    "background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #FF8C00, stop:1 #FFA500);"
    "}"
    "QPushButton:pressed {"
    "background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #B8860B, stop:1 #DAA520);"
    "}"
)
        self.abortProcess.setObjectName("abortProcess")
        self.processWindow1.raise_()
        self.groupBox.raise_()
        self.startProcess.raise_()
        self.abortProcess.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 546, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.statusbar.setStyleSheet("""
    border-style: inset;
    background-color: #e0e0e0; /* Light gray background */
    color: #333; /* Dark text color */
    font-weight: bold;
""")


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pot-O Media VA Extract v1.0.3.6-beta"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Source File"))
        self.sourceButton.setText(_translate("MainWindow", "Browse"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Extract to..."))
        self.targetButton.setText(_translate("MainWindow", "Browse"))
        self.processWindow1.setTitle(_translate("MainWindow", "Process Window"))
        self.startProcess.setText(_translate("MainWindow", "Start"))
        self.abortProcess.setText(_translate("MainWindow", "Abort or Exit"))
import assets_rc
